#
# Copyright (c) 2014 Francesco Balducci
#
# This file is part of arduino_c.
#
#    arduino_c is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    arduino_c is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with arduino_c.  If not, see <http://www.gnu.org/licenses/>.
#

PROG = timeswitch

SRC += timeswitch.c

include ../common/arduino.mk

